export const appConstants = {
    ADD_POSTS_REQUEST: "ADD_POSTS_REQUEST",
    ADD_POSTS_SUCCESS: "ADD_POSTS_SUCCESS",
    ADD_POSTS_FAILURE: "ADD_POSTS_FAILURE",

    GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
    GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
    GET_POSTS_FAILURE: "GET_POSTS_FAILURE"

}